name: Build Eureka Miner Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure Rust
        shell: powershell
        run: |
          rustup update stable
          rustup default stable
          rustc --version
          cargo --version

      - name: Build Eureka Miner
        run: cargo build --release

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: Eureka-Miner-Windows
          path: target/release/eureka-miner.exe
